name: Run Checkly Checks

# @TODO: change for production use
# on: [deployment_status]
on: [push]

env:
  CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
  CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
  # @TODO: change for production use
  CHECKLY_ENV: development

jobs:
  test-checkly:
    # @TODO: change for production use
    # if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Validate checkly config
        run: npx checkly deploy --preview

      - name: Run Checkly checks
        run: npx checkly test --record
